### ISSUE TITLE
source tcl on Windows

### ISSUE THREAD

**Issue by Naboki** [OVGN/OpenHBMC#10]
source C:\some_your_path\OpenHBMC\examples\mb_single_ram mb_single_ram.tcl
doesn't work on Windows, it generae an  "error: [common 17-165] too many positional options when parsing"
I had to use:
C:/some_your_path/OpenHBMC/examples/mb_single_ram/mb_single_ram.tcl
no spaces, no backslash and it's work fine.

**Comment by OVGN** [comment]
Hello!

Right, thanks a lot. There is a typo, a space before "mb_single_ram" instead of backslash.
BTW, both backslash and forward slash in the path are ok, vivado accepts both.
Have fixed readme.md

Best regards
