### ISSUE TITLE
How DRU works?

### ISSUE THREAD

**Issue by OVGN** [OVGN/OpenHBMC#5]
Hello!

This is some kind of discussion about DRU operation.
I think internals of this thread will be soon added to IP core documentation.

Feel free to ask question)

**Comment by OVGN** [comment]
The main difficulty with HyperBUS interface (in case we do not use/have DCARS feature) is sampling valid data during read transactions.

### Solution 1 (easiest and worst)
The most common way is to use HyperBUS clock CK_P/CK_N to sample data bus.
This method is quite simple, but also gives the worst result. Unfortunately tCKD time vary too much, i.e. CK_P/CK_N to data valid window is not stable at all. Of couse, probably this is going to work at low frequencies, but there is no chance to get reliable operation at high frequencies.

![tCKD_is_not_stable](https://user-images.githubusercontent.com/68017891/160728016-b91f2097-1164-4995-ac6d-3e1e89d4c395.png)



### Solution 2 (DLL based)
RWDS strobe is edge aligned to the incoming data DQ[7:0]. So we can shift RWDS to the center of the data eye. This method is much better than previous one, high operation frequencies can be easily achieved. But unfortunetely, there are some flaws, i.e. requirement of periodical calibration procedure. Also RWDS usually can be delayed by DLLs, that have some delay time limit, i.e. this is going to be impossible to shift RWDS to the center of data when HyperBUS clock frequency is low.

### Solution 3 (method used in OpenHMBC)
The idea of the OpenHMBC's DRU is to have durable PVT (Process, Temperature, Voltage) stable data recovery unit that do not need any kind of calibrations. DRU operation method is based on oversampling. Oversampling clock is 3x time faster than HyperBUS clock. RWDS and DQ[7:0] are sampled at both edges of the oversampling clock, so we have 6 samples for the period.

DRU algorithm is quite simple:
1. Detect any RWDS edge.
2. Next DQ[7:0] sample is valid.
3. Repeat...

![how_dru_works](https://user-images.githubusercontent.com/68017891/160728834-835ca6b8-1bd9-4137-a237-6037fa58c31b.png)

DRU do not sample data always at the center of the data eye, but guarantees to hit within sampling window, that in fact is much smaller than HyperRAM data valid window:

![dru_sample_window](https://user-images.githubusercontent.com/68017891/160729489-8b6f4eac-3381-42c0-a814-7de34efe60a5.png)

Sampling arrows movement shows that RWDS/DQ[7:0] can be fully asynchronous to the oversampling clock. At any phase relation DRU will hit within samling window.

![dru_sampling_animation](https://user-images.githubusercontent.com/68017891/160729852-95e66a48-e234-43d4-9532-305986c2772d.gif)

DRU operation was also proved in testbench, that will be published soon.

**Comment by richardc87** [comment]
This is awesome, thanks for posthing this.
